[2025-09-23 18:40:29] - [model_controller.py:214] - [WARNING]: The Config for the given baseline number (10) not found.
[2025-09-23 18:40:30] - [model_controller.py:32] - [ERROR]: The Model for the given baseline number (10) not found.
Traceback (most recent call last):
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/model_controller.py", line 30, in __init__
    self.model = self.load_model(self.baseline_number)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/model_controller.py", line 122, in load_model
    raise ValueError(
ValueError: The Model for the given baseline number (10) not found.
