[2025-09-22 20:11:08] - [train_controller.py:28] - [ERROR]: The Model for the given baseline number (10) not found
NoneType: None
[2025-09-22 20:13:17] - [train_controller.py:28] - [ERROR]: The Model for the given baseline number (10) not found
NoneType: None
[2025-09-22 20:16:52] - [train_controller.py:30] - [ERROR]: The Model for the given baseline number (%s) not found
Traceback (most recent call last):
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/train_controller.py", line 28, in __init__
    self.model = self.load_model(baseline_number)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/train_controller.py", line 117, in load_model
    raise ValueError("The Model for the given baseline number (%s) not found")
ValueError: The Model for the given baseline number (%s) not found
[2025-09-22 20:18:11] - [train_controller.py:30] - [ERROR]: The Model for the given baseline number (10) not found.
Traceback (most recent call last):
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/train_controller.py", line 28, in __init__
    self.model = self.load_model(baseline_number)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a_3llam/projects/deep-activity-recognition/src/controllers/train_controller.py", line 117, in load_model
    raise ValueError(
ValueError: The Model for the given baseline number (10) not found.
